#!/bin/bash

clientId=$(grep clientName secrets.json)
clientId=$(cut -d '"' -f4 <<< $clientId)
secret=$(grep clientSecretKey secrets.json)
secret=$(cut -d '"' -f4 <<< $secret)
clientUrl=$(grep keycloakAddress secrets.json)
clientUrl=$(cut -d '"' -f4 <<< $clientUrl)
clientUrl=$(cut -d '/' -f1 <<< $clientUrl)