AWSTemplateFormatVersion: 2010-09-09
Resources:
  SEAClientBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          - "-"
          - - Ref: AWS::StackName
            - "sea-client-data"
  PolicyForCognitoAuthed:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Join:
          - "-"
          - - Ref: AWS::StackName
            - "sea-client-policy"
            
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - !Sub ${SEAClientBucket.Arn}/${!aws:PrincipalTag/seaClientId}/inbound/*
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
            Resource:
              - !Sub ${SEAClientBucket.Arn}/${!aws:PrincipalTag/seaClientId}/outbound/*
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
            Resource:
              - !Sub arn:aws:sqs:us-east-1:${AWS::AccountId}:${AWS::StackName}-sea-client-${!aws:PrincipalTag/seaClientId}
Outputs:
  SEABucket:
    Description: The SEA client bucket
    Value: !Ref SEAClientBucket
    Export:
      Name: !Sub '${AWS::StackName}-SEAClientBucket'