AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SEABaseStack:
    Description: >-
      The name of the base SEA stack that provides the client bucket
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: sea1
  SEAClientId:
    Description: >-
      The name of this sea client (must match with seaClientId in JWT)
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: test-client
Resources:

  SEAClientSNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${SEABaseStack}-sea-client-${SEAClientId}

  SEAClientSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${SEABaseStack}-sea-client-${SEAClientId}

  SnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SEAClientSNS
      Endpoint: !GetAtt SEAClientSQS.Arn
      
  S3ToSnsTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Id: S3ToSnsTopicPolicy
          Version: '2012-10-17'
          Statement:
          - Sid: s3-to-sns-id
            Effect: Allow
            Principal:
              AWS: "*"
            Action: sns:Publish
            Resource: !Join [':', ['arn:aws:sns:us-east-1', Ref: 'AWS::AccountId', 's3-to-sns']]
            Condition:
              ArnLike:
                "AWS:SourceAccount": "056853049029"
        Topics:
        - !Ref SEAClientSNS